export type Product = {
  id: string;
  number: number;
  name: string;
  nameJa: string;
  description: string;
  price: number;
  category: string;
  benefits: string[];
  size: string;
  image: string;
  featured: boolean;
};

export const products: Product[] = [
  // 5ml シリーズ
  {
    id: "kuromoji-5ml",
    number: 1,
    name: "Kuromoji",
    nameJa: "クロモジ",
    description: "リナロール主成分で、高級香水にも使用されるローズウッドと同じ主成分を持つ稀少なオイル。スズランのような甘く優雅な香り。",
    price: 16830,
    category: "5ml",
    benefits: ["甘く優雅な香り", "高級感", "森林浴"],
    size: "5ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2025/01/DSC_7738_1.jpeg",
    featured: true,
  },
  {
    id: "akitasugi-5ml",
    number: 2,
    name: "Akita Sugi",
    nameJa: "アキタスギ",
    description: "α-ピネン、オイデスモール等を含む。懐かしい杉の香りで安らぎを感じさせる、秋田を代表する銘木のオイル。",
    price: 5060,
    category: "5ml",
    benefits: ["安らぎ", "消臭", "リフレッシュ"],
    size: "5ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2025/01/DSC_7727_1.jpeg",
    featured: true,
  },
  {
    id: "aomoritodomatsu-5ml",
    number: 3,
    name: "Aomori Todomatsu",
    nameJa: "アオモリトドマツ",
    description: "希少なボルニルアセテートを主成分とする。気高く爽やかで凛とした「森の香り」。",
    price: 15400,
    category: "5ml",
    benefits: ["森林浴", "リフレッシュ", "凛とした香り"],
    size: "5ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2025/01/DSC_7732_1.jpeg",
    featured: true,
  },
  {
    id: "nanbuakamatsu-5ml",
    number: 4,
    name: "Nanbu Akamatsu",
    nameJa: "ナンブアカマツ",
    description: "α-ピネン、β-ピネンを多く含む。フレッシュな森林の香りが広がる南部赤松のオイル。",
    price: 5060,
    category: "5ml",
    benefits: ["森林浴", "集中力UP", "消臭"],
    size: "5ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2025/01/DSC_7720_1.jpeg",
    featured: false,
  },
  {
    id: "urajiromomi-5ml",
    number: 5,
    name: "Urajiro Momi",
    nameJa: "ウラジロモミ",
    description: "ジントニックを思わせる清楚で凛とした香り。爽やかでフレッシュな希少なオイル。",
    price: 5060,
    category: "5ml",
    benefits: ["清涼感", "爽やかな香り", "フレッシュ"],
    size: "5ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2025/01/DSC_7730_1.jpeg",
    featured: false,
  },
  {
    id: "nioihiba-5ml",
    number: 6,
    name: "Nioi Hiba",
    nameJa: "ニオイヒバ",
    description: "柑橘系を含む刺激的でフルーティーな強い芳香。きりりとした清涼感が特徴。",
    price: 7700,
    category: "5ml",
    benefits: ["清涼感", "消臭", "リフレッシュ"],
    size: "5ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2025/01/DSC_7723_1.jpeg",
    featured: true,
  },
  {
    id: "hinoki-5ml",
    number: 7,
    name: "Hinoki",
    nameJa: "ヒノキ",
    description: "α-ピネン、リモネン成分を多く含む。日本人に最も馴染み深い、懐かしく親しみのある香り。",
    price: 5060,
    category: "5ml",
    benefits: ["安らぎ", "リラックス", "消臭"],
    size: "5ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2025/01/DSC_7742_1.jpeg",
    featured: false,
  },
  {
    id: "goyoumatsu-5ml",
    number: 8,
    name: "Goyo Matsu",
    nameJa: "ゴヨウマツ",
    description: "ネロリドールを多く含む。甘くスッキリとした爽やかな香りの五葉松オイル。",
    price: 7700,
    category: "5ml",
    benefits: ["爽やか", "リフレッシュ", "集中力UP"],
    size: "5ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2025/01/DSC_7721_1.jpeg",
    featured: false,
  },
  {
    id: "asunaro-5ml",
    number: 9,
    name: "Asunaro",
    nameJa: "アスナロ",
    description: "α・β-ピネン、ヒノキチオールを含有。樟脳のようなフレッシュな香りが特徴。",
    price: 5060,
    category: "5ml",
    benefits: ["フレッシュ", "清々しい香り", "消臭"],
    size: "5ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2025/01/DSC_7725_1.jpeg",
    featured: false,
  },
  {
    id: "sawara-5ml",
    number: 10,
    name: "Sawara",
    nameJa: "サワラ",
    description: "α-ピネン、酢酸ボルニルを多く含む。丸みのある森林浴のような優しい香り。",
    price: 7700,
    category: "5ml",
    benefits: ["森林浴", "安らぎ", "リラックス"],
    size: "5ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2025/01/DSC_7739_1.jpeg",
    featured: false,
  },
  {
    id: "itohiba-5ml",
    number: 11,
    name: "Ito Hiba",
    nameJa: "イトヒバ",
    description: "オレンジなどの柑橘系のすっきりした香りを持つ希少なオイル。",
    price: 7700,
    category: "5ml",
    benefits: ["柑橘系", "すっきり", "消臭"],
    size: "5ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2025/01/DSC_7733_1.jpeg",
    featured: false,
  },
  // 1ml シリーズ
  {
    id: "kuromoji-1ml",
    number: 1,
    name: "Kuromoji",
    nameJa: "クロモジ",
    description: "リナロール主成分で、高級香水にも使用されるローズウッドと同じ主成分を持つ稀少なオイル。スズランのような甘く優雅な香り。",
    price: 4400,
    category: "1ml",
    benefits: ["甘く優雅な香り", "高級感", "森林浴"],
    size: "1ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2024/11/No1%E3%82%AF%E3%83%AD%E3%83%A2%E3%82%B8_2.jpeg",
    featured: false,
  },
  {
    id: "akitasugi-1ml",
    number: 2,
    name: "Akita Sugi",
    nameJa: "アキタスギ",
    description: "α-ピネン、オイデスモール等を含む。懐かしい杉の香りで安らぎを感じさせる、秋田を代表する銘木のオイル。",
    price: 1848,
    category: "1ml",
    benefits: ["安らぎ", "消臭", "リフレッシュ"],
    size: "1ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2024/11/No2%E3%82%A2%E3%82%AD%E3%82%BF%E3%82%B9%E3%82%AE_2.jpeg",
    featured: false,
  },
  {
    id: "aomoritodomatsu-1ml",
    number: 3,
    name: "Aomori Todomatsu",
    nameJa: "アオモリトドマツ",
    description: "希少なボルニルアセテートを主成分とする。気高く爽やかで凛とした「森の香り」。",
    price: 3300,
    category: "1ml",
    benefits: ["森林浴", "リフレッシュ", "凛とした香り"],
    size: "1ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2024/11/No3%E3%82%A2%E3%82%AA%E3%83%A2%E3%83%AA%E3%83%88%E3%83%89%E3%83%9E%E3%83%84_2.jpeg",
    featured: false,
  },
  {
    id: "nanbuakamatsu-1ml",
    number: 4,
    name: "Nanbu Akamatsu",
    nameJa: "ナンブアカマツ",
    description: "α-ピネン、β-ピネンを多く含む。フレッシュな森林の香りが広がる南部赤松のオイル。",
    price: 1848,
    category: "1ml",
    benefits: ["森林浴", "集中力UP", "消臭"],
    size: "1ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2024/11/No4%E3%83%8A%E3%83%B3%E3%83%96%E3%82%A2%E3%82%AB%E3%83%9E%E3%83%84_2.jpeg",
    featured: false,
  },
  {
    id: "urajiromomi-1ml",
    number: 5,
    name: "Urajiro Momi",
    nameJa: "ウラジロモミ",
    description: "ジントニックを思わせる清楚で凛とした香り。爽やかでフレッシュな希少なオイル。",
    price: 1848,
    category: "1ml",
    benefits: ["清涼感", "爽やかな香り", "フレッシュ"],
    size: "1ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2024/11/No5%E3%82%A6%E3%83%A9%E3%82%B8%E3%83%AD%E3%83%A2%E3%83%9F_2.jpeg",
    featured: false,
  },
  {
    id: "nioihiba-1ml",
    number: 6,
    name: "Nioi Hiba",
    nameJa: "ニオイヒバ",
    description: "柑橘系を含む刺激的でフルーティーな強い芳香。きりりとした清涼感が特徴。",
    price: 2156,
    category: "1ml",
    benefits: ["清涼感", "消臭", "リフレッシュ"],
    size: "1ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2024/11/No6%E3%83%8B%E3%82%AA%E3%82%A4%E3%83%92%E3%83%90_2.jpeg",
    featured: false,
  },
  {
    id: "hinoki-1ml",
    number: 7,
    name: "Hinoki",
    nameJa: "ヒノキ",
    description: "α-ピネン、リモネン成分を多く含む。日本人に最も馴染み深い、懐かしく親しみのある香り。",
    price: 1848,
    category: "1ml",
    benefits: ["安らぎ", "リラックス", "消臭"],
    size: "1ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2024/11/No7%E3%83%92%E3%83%8E%E3%82%AD_2.jpeg",
    featured: false,
  },
  {
    id: "goyoumatsu-1ml",
    number: 8,
    name: "Goyo Matsu",
    nameJa: "ゴヨウマツ",
    description: "ネロリドールを多く含む。甘くスッキリとした爽やかな香りの五葉松オイル。",
    price: 2156,
    category: "1ml",
    benefits: ["爽やか", "リフレッシュ", "集中力UP"],
    size: "1ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2024/11/No8%E3%82%B4%E3%83%A8%E3%82%A6%E3%83%9E%E3%83%84_2.jpeg",
    featured: false,
  },
  {
    id: "asunaro-1ml",
    number: 9,
    name: "Asunaro",
    nameJa: "アスナロ",
    description: "α・β-ピネン、ヒノキチオールを含有。樟脳のようなフレッシュな香りが特徴。",
    price: 1848,
    category: "1ml",
    benefits: ["フレッシュ", "清々しい香り", "消臭"],
    size: "1ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2024/11/No9%E3%82%A2%E3%82%B9%E3%83%8A%E3%83%AD_2.jpeg",
    featured: false,
  },
  {
    id: "sawara-1ml",
    number: 10,
    name: "Sawara",
    nameJa: "サワラ",
    description: "α-ピネン、酢酸ボルニルを多く含む。丸みのある森林浴のような優しい香り。",
    price: 2156,
    category: "1ml",
    benefits: ["森林浴", "安らぎ", "リラックス"],
    size: "1ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2024/11/No10%E3%82%B5%E3%83%AF%E3%83%A9_2.jpeg",
    featured: false,
  },
  {
    id: "itohiba-1ml",
    number: 11,
    name: "Ito Hiba",
    nameJa: "イトヒバ",
    description: "オレンジなどの柑橘系のすっきりした香りを持つ希少なオイル。",
    price: 2156,
    category: "1ml",
    benefits: ["柑橘系", "すっきり", "消臭"],
    size: "1ml",
    image: "https://kitaguninomori.com/wp-content/uploads/2024/11/No11%E3%82%A4%E3%83%88%E3%83%92%E3%83%90_2.jpeg",
    featured: false,
  },
];

export const categories = ["すべて", "5ml", "1ml"];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getAlternativeSize(id: string): Product | undefined {
  const current = products.find((p) => p.id === id);
  if (!current) return undefined;
  return products.find((p) => p.name === current.name && p.id !== current.id);
}

export function getRelatedProducts(id: string, limit: number = 4): Product[] {
  const current = products.find((p) => p.id === id);
  if (!current) return [];
  return products
    .filter((p) => p.category === current.category && p.id !== current.id)
    .slice(0, limit);
}
